name: Build php images

on:
  push:
    branches:
      - master

    tags:
      - v*

env:
  IMAGE_NAME_NGINX: nginx
  IMAGE_NAME_FPM: fpm-alpine
  IMAGE_NAME_FPM_DEV: fpm-dev

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build the php fpm image
      run: |
        docker build fpm --tag $IMAGE_NAME_FPM

    - name: Build the php fpm development image
      run: |
        docker build fpm-dev --tag $IMAGE_NAME_FPM_DEV

    - name: Build the php with nginx image
      run: |
        docker build nginx --tag $IMAGE_NAME_NGINX

    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push images to docker hub
      run: |
        IMAGE_ID=${{ github.repository }}
        # Change all uppercase to lowercase
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

        # Strip git ref prefix from version
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        # Strip "v" prefix from tag name
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

        # Use Docker `latest` tag convention
        [ "$VERSION" == "master" ] && VERSION=latest

        echo "Pushing image $IMAGE_ID:$VERSION-fpm-alpine"
        docker tag $IMAGE_NAME_FPM $IMAGE_ID:$VERSION-fpm-alpine
        docker push $IMAGE_ID:$VERSION-fpm-alpine

        echo "Pushing image $IMAGE_ID:$VERSION-fpm-dev"
        docker tag $IMAGE_NAME_FPM_DEV $IMAGE_ID:$VERSION-fpm-dev
        docker push $IMAGE_ID:$VERSION-fpm-dev

        echo "Pushing image $IMAGE_ID:$VERSION-nginx"
        docker tag $IMAGE_NAME_NGINX $IMAGE_ID:$VERSION-nginx
        docker push $IMAGE_ID:$VERSION-nginx
